var g = [ {
    imgBig: "../../images/入门新手.png",
    imgTxt: "../../images/入门新手(1).png"
}, {
    imgBig: "../../images/菜鸟铸铁.png",
    imgTxt: "../../images/菜鸟铸铁(1).png"
}, {
    imgBig: "../../images/不屈黑铁.png",
    imgTxt: "../../images/不屈黑铁(1).png"
}, {
    imgBig: "../../images/倔犟寒铁.png",
    imgTxt: "../../images/倔犟寒铁(1).png"
}, {
    imgBig: "../../images/坚毅玄铁.png",
    imgTxt: "../../images/坚毅玄铁(1).png"
}, {
    imgBig: "../../images/机敏青铜.png",
    imgTxt: "../../images/机敏青铜(1).png"
}, {
    imgBig: "../../images/优秀黄铜.png",
    imgTxt: "../../images/优秀黄铜(1).png"
}, {
    imgBig: "../../images/杰出白银.png",
    imgTxt: "../../images/杰出白银(1).png"
}, {
    imgBig: "../../images/卓越黄金.png",
    imgTxt: "../../images/卓越黄金(1).png"
}, {
    imgBig: "../../images/璀璨铂金.png",
    imgTxt: "../../images/璀璨铂金(1).png"
}, {
    imgBig: "../../images/精英振金.png",
    imgTxt: "../../images/精英振金(1).png"
}, {
    imgBig: "../../images/睿智翡翠.png",
    imgTxt: "../../images/睿智翡翠(1).png"
}, {
    imgBig: "../../images/如炬钻石.png",
    imgTxt: "../../images/如炬钻石(1).png"
}, {
    imgBig: "../../images/卓越大师.png",
    imgTxt: "../../images/卓越大师(1).png"
}, {
    imgBig: "../../images/一代宗师.png",
    imgTxt: "../../images/一代宗师(1).png"
}, {
    imgBig: "../../images/超凡宗师.png",
    imgTxt: "../../images/超凡宗师(1).png"
}, {
    imgBig: "../../images/超强王者.png",
    imgTxt: "../../images/超强王者(1).png"
}, {
    imgBig: "../../images/至尊王者.png",
    imgTxt: "../../images/至尊王者(1).png"
} ];

module.exports = {
    rankList: g
};